### PR TITLE
Analysis of spin probe data

### PR DESCRIPTION
**Pull request by jchodera**
This PR adds scripts to analyze EPR spin probe simulations (PROJ11431).

### CODE REVIEW

**Comment by jchodera** [comment]
@sonyahanson : Take a look at the [`README.md`](https://github.com/choderalab/AURKA_UMN/blob/spin-probes/spin-probe-analysis/README.md) for documentation.

Go ahead and merge this PR and take over!

I'll still be working on `Visualize.ipynb` (which does not work yet), but you should feel free to dig into the actual trajectory data on `plfah1` and visualize it however you like!

**Comment by sonyahanson** [comment]
Can I ask how these distances were decided on?
The readme says this, but I don't find this clarifying:
index 3 : F275 CZ - I193 CG2 distance (low in DFG-in)
index 4 : W277 CE2 - I193 CG2 distance (low in DFG-out)

```python
# Determine F275 CZ - I193 CG2 distance
DFG_PHE_ILE = traj.top.select('(resSeq %d and resname PHE and name CZ) or (resSeq %d and resname ILE and name CG2)' % (275 - offset + 1, 193 - offset + 1))
 
# Determine W277 CE2 - I193 CG2 distance
DFG_TRP_ILE = traj.top.select('(resSeq %d and resname TRP and name CE2) or (resSeq %d and resname ILE and name CG2)' % (277 - offset + 1, 193 - offset + 1))
```

Are these from experiment? Should I use these to look for DFG-flips as Nick requested?

If I was just asked to identify DFG-flips in a void, I would use the coordinate I've been using for Src, Abl, and DDR1: F275 CZ - A243 CA distance

I'm happy to look at all of these distances, but just would like to be informed.

**Comment by sonyahanson** [comment]
Also, does what Nick is asking for require just analyzing these runs?
```
11418: AurA -TPX2, pdb 1OL5
RUN0: WT
RUN1: WT
RUN2: WT
RUN3: WT
RUN4: WT
```

**Comment by jchodera** [comment]
> Can I ask how these distances were decided on?

Nick specifically suggested these in a Skype call in which I asked which distances might be indicative of a DFG flip. In a DFG-in state, the sidechain of F275 fits into a pocket lined by I293. When the DFG loop flips, the F275 sidechain is removed from that pocket and W277 rotates into place in its stead.

**Comment by jchodera** [comment]
> If I was just asked to identify DFG-flips in a void, I would use the coordinate I've been using for Src, Abl, and DDR1: F275 CZ - A243 CA distance

I don't know if this coordinate has a particular biophysical driving force. As I noted above, the sidechain of W277 appears to fill the pocket when F275 rotates out.

**Comment by jchodera** [comment]
> Also, does what Nick is asking for require just analyzing these runs?
> 11418: AurA -TPX2, pdb 1OL5
> RUN0: WT
> RUN1: WT
> RUN2: WT
> RUN3: WT
> RUN4: WT

The spin probe data is all 11431, but I believe Nick is interested in what happens with phosphorylation both in the spin-probe simulations (11431) and in the unlabeled wild-type phosphorylated simulations (11428/11429) vs the wild-type nonphosphorylated simulations. @steven-albanese did all the analysis for the phosphoryated/unphosphorylated simulations, so he can point you to the scripts he used there---this PR only contains analysis of 11431 spin-probe simulations.

**Comment by sonyahanson** [comment]
Gonna go ahead and merge this.

**Comment by jchodera** [comment]
Go for it!

**Pull request merged**
